config/routes.rb
Rails.application.routes.draw do
  resources :questions, :only => [:new, :show]
  get 'questions' => 'questions#new'
  post 'questions' => 'questions#show'

  resources :ops_job_states

end

app/models/ops_job_state.rb
class OpsJobState < ActiveRecord::Base
  self.table_name = 'tpcom.ops_job_state'
  # attr_accessor PROVIDES

  scope :jobstate_w_jobname, lambda { |term| where('job_name = ?', "#{term}") }

  ID_REGISTER[:JOB_NAME] = {
      is_primary: false,
      OpsJobState: {
          jobstate_w_jobname: {
              priority: 1,
              with: ['JOB_NAME'],
              handle: 'jobstate_w_jobname'
          }
      }
  }

end

app/models/purchase_order2.rb
class PurchaseOrder2 < ActiveRecord::Base
  self.table_name = "tpcom.purchaseorder2"
  # attr_accessor PROVIDES

  default_scope lambda { |term| where("purchaseorderid = ?", "%#{term}%") }
  scope :mastpoid_w_poid, lambda { |term| where("purchaseorderid = ? AND masterpurchaseorderid is not null", "%#{term}%") }
  scope :poid_w_ponum_a_mcid, lambda { |term| where("purchaseordernumber = ? ANand (sellermembercompanyid = ? or buyermembercompanyid = ?) and purchaseorderid is not null", "%#{term}%") }


  ID_REGISTER[:MASTERPURCHASEORDERID] = {
      is_primary: true,
      PurchaseOrder2: {
          mastpoid_w_poid: {
              priority: 1,
              with: ['PURCHASEORDERID'],
              handle: 'mastpoid_w_poid'
          }
      }
  }

  ID_REGISTER[:PURCHASEORDERID] = {
      is_primary: true,
      PurchaseOrder2: {
          poid_w_ponum_a_bmcid: {
              priority: 1,
              with: ['PURCHASEORDERNUMBER','BUYERMEMBERCOMPANYID','BUYERMEMBERCOMPANYID'],
              handle: 'poid_w_ponum_a_mcid'
          },
          poid_w_ponum_a_smcid: {
              priority: 1,
              with: ['PURCHASEORDERNUMBER','SELLERMEMBERCOMPANYID','SELLERMEMBERCOMPANYID'],
              handle: 'poid_w_ponum_a_mcid'
          }
      }
  }

end

app/models/question.rb
class Question
  include ActiveModel::Model
  extend ActiveModel::Callbacks

  define_model_callbacks :save
  attr_accessor :id, :simple_key, :simple_value

  validates :simple_value, presence: true, length: {in:4..25}
  validates_inclusion_of :simple_key, :in => SIMPLE_KEY_CHOICES

  # def save
  #   if valid?
  #     run_callbacks(:save) { true }
  #   else
  #     false
  #   end
  # end
  #
  # def persisted?
  #   self.id == 1
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/ops_job_states_controller.rb
class OpsJobStatesController < ApplicationController
  # before_action :set_ops_job_state, only: [:show, :edit, :update, :destroy]
  # before_action :set_ops_job_state

  # GET /ops_job_states
  # GET /ops_job_states.json
  def index
    @ops_job_state = OpsJobState.new
    @ops_job_states = OpsJobState.jobstate_w_jobname('MLH_TEST1.JOB1')
  end

  # GET /ops_job_states/1
  # GET /ops_job_states/1.json
  def show
  end

  # GET /ops_job_states/new
  # def new
  #   @ops_job_state = OpsJobState.new
  # end

  # GET /ops_job_states/1/edit
  # def edit
  # end

  # POST /ops_job_states
  # POST /ops_job_states.json
  # def create
  #   @ops_job_state = OpsJobState.new(ops_job_state_params)
  #
  #   respond_to do |format|
  #     if @ops_job_state.save
  #       format.html { redirect_to @ops_job_state, notice: 'Ops job state was successfully created.' }
  #       format.json { render :show, status: :created, location: @ops_job_state }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @ops_job_state.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /ops_job_states/1
  # PATCH/PUT /ops_job_states/1.json
  # def update
  #   respond_to do |format|
  #     if @ops_job_state.update(ops_job_state_params)
  #       format.html { redirect_to @ops_job_state, notice: 'Ops job state was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @ops_job_state }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @ops_job_state.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /ops_job_states/1
  # DELETE /ops_job_states/1.json
  # def destroy
  #   @ops_job_state.destroy
  #   respond_to do |format|
  #     format.html { redirect_to ops_job_states_url, notice: 'Ops job state was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_ops_job_state
    #   @ops_job_state = OpsJobState.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ops_job_state_params
      params.require(:ops_job_state).permit(:job_name, :date_started, :date_completed, :status, :message)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_primaries, only: [:show, :new]

  # GET /questions
  # GET /questions.json
  # def index
  #   @questions = Question.all
  # end


  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.new(question_params)

    if @question.valid?
      flash[:notice]='Question was successfully created.'
      render :show
    else
      render :new
    end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  # def edit
  # end

  # POST /questions
  # POST /questions.json
  # def create
  #   @question = Question.new(question_params)
  #
  #   respond_to do |format|
  #     if @question.save
  #       format.html { render :show, notice: 'Question was successfully created.' }
  #       format.json { render :show, status: :created, location: @question }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  # def update
  #   respond_to do |format|
  #     if @question.update(question_params)
  #       format.html { redirect_to @question, notice: 'Question was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @question }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @question.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /questions/1
  # DELETE /questions/1.json
  # def destroy
  #   @question.destroy
  #   respond_to do |format|
  #     format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  def get_primaries
    @primaries = Array.new
    ID_REGISTER.each do |key, val|
       if val.has_key?(:is_primary) && val[:is_primary]
         @primaries.push( "#{key}" )
       end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:simple_key, :simple_value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ops_job_states_helper.rb
module OpsJobStatesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carnac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ops_job_states/_form.html.erb
<%= form_for(@ops_job_state) do |f| %>
  <% if @ops_job_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ops_job_state.errors.count, "error") %> prohibited this ops_job_state from being saved:</h2>

      <ul>
      <% @ops_job_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_name %><br>
    <%= f.text_field :job_name %>
  </div>
  <div class="field">
    <%= f.label :date_started %><br>
    <%= f.datetime_select :date_started %>
  </div>
  <div class="field">
    <%= f.label :date_completed %><br>
    <%= f.datetime_select :date_completed %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ops_job_states/edit.html.erb
<h1>Editing ops_job_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @ops_job_state %> |
<%= link_to 'Back', ops_job_states_path %>

app/views/ops_job_states/index.html.erb
<h1>Listing ops_job_states</h1>

<%= form_for(@ops_job_state) do |f| %>
  <div class="field">
      <%= f.label :job_name %><br>
      <%= f.text_field :job_name %>
  </div>
<% end %>

<hr>

<table>
  <thead>
    <tr>
      <th>Job name</th>
      <th>Date started</th>
      <th>Date completed</th>
      <th>Status</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ops_job_states.each do |ops_job_state| %>
      <tr>
        <td><%= ops_job_state.job_name %></td>
        <td><%= ops_job_state.date_started %></td>
        <td><%= ops_job_state.date_completed %></td>
        <td><%= ops_job_state.status %></td>
        <td><%= ops_job_state.message %></td>
        <td><%= link_to 'Show', ops_job_state %></td>
        <td><%= link_to 'Edit', edit_ops_job_state_path(ops_job_state) %></td>
        <td><%= link_to 'Destroy', ops_job_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ops job state', new_ops_job_state_path %>

app/views/ops_job_states/new.html.erb
<h1>New ops_job_state</h1>

<%= render 'form' %>

<%= link_to 'Back', ops_job_states_path %>

app/views/ops_job_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job name:</strong>
  <%= @ops_job_state.job_name %>
</p>

<p>
  <strong>Date started:</strong>
  <%= @ops_job_state.date_started %>
</p>

<p>
  <strong>Date completed:</strong>
  <%= @ops_job_state.date_completed %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ops_job_state.status %>
</p>

<p>
  <strong>Message:</strong>
  <%= @ops_job_state.message %>
</p>

<%= link_to 'Edit', edit_ops_job_state_path(@ops_job_state) %> |
<%= link_to 'Back', ops_job_states_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select(:simple_key, @primaries, {:include_blank => 'Must select one'}) %>
  </div>
  <div class="field">
    <%= f.label :simple_value %><br>
    <%= f.text_field :simple_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Simple key</th>
      <th>Simple value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.simple_key %></td>
        <td><%= question.simple_value %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Simple key:</strong>
  <%= @question.simple_key %>
</p>

<p>
  <strong>Simple value:</strong>
  <%= @question.simple_value %>
</p>

<%= link_to 'Back', questions_path %>